name: fridgeai
description: Analyse ton frigo et génère des recettes avec l'IA.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1  # <--- ICI le changement

flutter:
  uses-material-design: true
  generate: true
